### ISSUE TITLE
Question about the correct way to enforce semi orthogonality

### ISSUE THREAD

**Issue by kwasnydam** [cvqluu/Factorized-TDNN#2]
Hey man, and thank you for this great repository, it saved me from implementing and debugging TDNN/FTDNN and instead I can focus on experiments. I have one question regarding the correct way to step the optimizer, because it seems that I have been doing it wrong until now. After reading the "usage" part of the README it seems to me that the correct way to step during the training is to do something like that: assuming that the most basic way to train network in pytorch is to:
```
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
``` 

and you wrote 
```
tdnn_f.step_semi_orth() # The key method to constrain the first two convolutions, perform after every SGD step
```
Than I should add this call `tdnn_f.step_semi_orth()` after the `optimizer.step()` call, making it like this, right?
```
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
    tdnn_f.step_semi_orth()
```

Thank you for your time if you happen to answer this question!

**Comment by cvqluu** [comment]
Yes that seems right (to take an orth step at every SGD step)
