### ISSUE TITLE
Pre-processing and training data

### ISSUE THREAD

**Issue by nelaturuharsha** [cvqluu/Factorized-TDNN#3]
Hello!

Thank you so much for the great work you've shared, would it possible for you to share the pre-processing methodology and the training data you worked with as a demo.

It would be great help.

Thank you!

**Comment by cvqluu** [comment]
Hi, 

I'm just leaving this repo up as a very simple snippet for the models alone. 

If you'd like more info on the preprocessing and the whole pipeline, check out [https://github.com/cvqluu/dropclass_speaker](https://github.com/cvqluu/dropclass_speaker) which has a bit more information on how to run this completely, and it includes information on data processing.

Specifically you would make a config file with the `model = FTDNN` set.

If you have any further questions there feel free to bring them up on that repo.

Hope that helps,
Chau
